import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import PersonasProvider from '@/hooks/context/PersonasProvider';

const inter = Roboto({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
interface Props {
    children: React.ReactNode;
}
export default function RootLayout({ children }: Props) {
    return (
        <html lang='es'>
            <body className={inter.className}>
                <main className='main'>
                    <PersonasProvider>{children}</PersonasProvider>
                </main>
            </body>
        </html>
    );
}
